#!/usr/bin/env bash
# Flash the sscma_server_at firmware (built by build_fw.sh) to the XIAO
# ESP32S3 Sense over its native USB-Serial-JTAG port.
#
# Usage:
#   ./scripts/flash_fw.sh [--port /dev/cu.usbmodemXXX]
#
# Requires on the host: python3 with venv support. The first run creates
# scripts/.venv and installs scripts/requirements.txt (esptool + pyserial)
# into it; later runs reuse that venv as-is.
#
# Runs on the HOST (Docker on macOS cannot reach USB). The port is
# auto-detected (VID 0x303A / PID 0x1001, the XIAO's native USB-Serial-JTAG)
# unless --port is given.
#
# Recovery / bootloader-catch notes (hard-won on this hardware):
#   * A crash-looping firmware flaps USB enumeration and can wedge the macOS
#     USB-Serial-JTAG session: the /dev/cu.usbmodem* node stays present but
#     ALL I/O is dead, and no software reset (DTR/RTS dance included) revives
#     it. Only a PHYSICAL replug fixes a wedged session -- if this script
#     cannot connect at all, replug the board first.
#   * If the running firmware is too broken for the automatic reset-to-
#     bootloader to work, catch the ROM bootloader manually: hold BOOT, tap
#     RESET, release BOOT. The board re-enumerates in download mode (the
#     usbmodem number may change) and esptool connects immediately.
#   * --connect-attempts 15 rides out the re-enumeration window after a
#     reset: on macOS the port node disappears and returns a beat later, so
#     the first few attempts routinely fail even on a healthy board.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BUILD_DIR="$REPO_ROOT/build/sscma_server_at"
VENV_DIR="$SCRIPT_DIR/.venv"

if [[ ! -x "$VENV_DIR/bin/python3" ]]; then
  echo "[flash_fw] creating venv at $VENV_DIR"
  python3 -m venv "$VENV_DIR"
  "$VENV_DIR/bin/python3" -m pip install --quiet --upgrade pip
  "$VENV_DIR/bin/python3" -m pip install --quiet -r "$SCRIPT_DIR/requirements.txt"
fi
PYTHON3="$VENV_DIR/bin/python3"

PORT=""
while [[ $# -gt 0 ]]; do
  case $1 in
    --port) PORT="$2"; shift ;;
    *) echo "Unknown argument: $1"; echo "Usage: $0 [--port /dev/cu.usbmodemXXX]"; exit 1 ;;
  esac
  shift
done

[[ -f "$BUILD_DIR/flash_args" ]] || {
  echo "Error: no build at $BUILD_DIR (flash_args missing)."
  echo "Run scripts/build_fw.sh first."
  exit 1
}

if [[ -z "$PORT" ]]; then
  PORT=$("$PYTHON3" -c "
import serial.tools.list_ports as lp
matches = [p.device for p in lp.comports() if p.vid == 0x303A and p.pid == 0x1001]
print(matches[0] if matches else '')
" 2>/dev/null || true)
  [[ -n "$PORT" ]] || {
    echo "Error: no XIAO ESP32S3 found (VID 0x303A / PID 0x1001)."
    echo "Pass --port explicitly, or replug the board if the session is wedged."
    exit 1
  }
fi

echo "[flash_fw] port: $PORT"
echo "[flash_fw] build: $BUILD_DIR"

# @flash_args expands to the full offset/file list generated by idf.py
# (bootloader @0x0, partition table @0x8000, app @0x40000, ...) with paths
# RELATIVE to the build dir -- hence the cd. This flashes exactly what idf.py
# flash would, minus the need for IDF on the host.
#
# --after hard-reset: boot straight into the freshly flashed app; the USJ
# port will re-enumerate (possibly under a new usbmodem number), which is
# normal -- reconnect tools should re-detect the port.
cd "$BUILD_DIR"
"$PYTHON3" -m esptool \
  --chip esp32s3 \
  --port "$PORT" \
  --baud 921600 \
  --connect-attempts 15 \
  --before default-reset \
  --after hard-reset \
  write-flash @flash_args

echo "[flash_fw] done -- board is rebooting into the new firmware."
